In [1]:
# Decision Tree Regression

# Importing necessary libraries
import numpy as np  # For numerical operations
import matplotlib.pyplot as plt  # For visualization
import pandas as pd  # For handling datasets

# Importing the dataset
dataset = pd.read_csv('Data.csv')  # Load dataset (replace with actual filename)
X = dataset.iloc[:, :-1].values  # Selecting all columns except the last one as features (independent variables)
y = dataset.iloc[:, -1].values  # Selecting the last column as the target variable (dependent variable)

# Splitting the dataset into Training and Test sets
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)
# 80% training data, 20% testing data

# Training the Decision Tree Regression model
from sklearn.tree import DecisionTreeRegressor
regressor = DecisionTreeRegressor(random_state=0)  # Creating the Decision Tree Regressor
regressor.fit(X_train, y_train)  # Training the model on training data

# Making Predictions on the Test Set
y_pred = regressor.predict(X_test)

# Displaying the Predicted vs Actual Values
np.set_printoptions(precision=2)  # Set precision for better readability
print("\nPredicted vs Actual values:\n")
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)), 1))

# Evaluating the Model
from sklearn.metrics import r2_score
r2 = r2_score(y_test, y_pred)  # Compute R² score
print("\nR² Score: {:.2f}".format(r2))  # Print R² score with two decimal places



Predicted vs Actual values:

[[431.28 431.23]
 [459.59 460.01]
 [460.06 461.14]
 ...
 [471.46 473.26]
 [437.76 438.  ]
 [462.74 463.28]]

R² Score: 0.92


In [2]:
# Multiple Linear Regression

# Importing necessary libraries
import numpy as np  # For numerical operations
import matplotlib.pyplot as plt  # For visualization
import pandas as pd  # For handling datasets

# Importing the dataset
dataset = pd.read_csv('Data.csv')  # Load dataset (replace with actual filename)
X = dataset.iloc[:, :-1].values  # Selecting all columns except the last one as features (independent variables)
y = dataset.iloc[:, -1].values  # Selecting the last column as the target variable (dependent variable)

# Splitting the dataset into Training and Test sets
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)
# 80% training data, 20% testing data

# Training the Multiple Linear Regression model
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()  # Creating the Linear Regression model
regressor.fit(X_train, y_train)  # Training the model on training data

# Making Predictions on the Test Set
y_pred = regressor.predict(X_test)

# Displaying the Predicted vs Actual Values
np.set_printoptions(precision=2)  # Set precision for better readability
print("\nPredicted vs Actual values:\n")
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)), 1))

# Evaluating the Model
from sklearn.metrics import r2_score
r2 = r2_score(y_test, y_pred)  # Compute R² score
print("\nR² Score: {:.2f}".format(r2))  # Print R² score with two decimal places



Predicted vs Actual values:

[[431.43 431.23]
 [458.56 460.01]
 [462.75 461.14]
 ...
 [469.52 473.26]
 [442.42 438.  ]
 [461.88 463.28]]

R² Score: 0.93


In [3]:
# Polynomial Regression

# Importing necessary libraries
import numpy as np  # For numerical operations
import matplotlib.pyplot as plt  # For visualization
import pandas as pd  # For handling datasets

# Importing the dataset
dataset = pd.read_csv('Data.csv')  # Load dataset (replace with actual filename)
X = dataset.iloc[:, :-1].values  # Selecting all columns except the last one as features (independent variables)
y = dataset.iloc[:, -1].values  # Selecting the last column as the target variable (dependent variable)

# Splitting the dataset into Training and Test sets
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)
# 80% training data, 20% testing data

# Transforming Features for Polynomial Regression
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression

poly_reg = PolynomialFeatures(degree=4)  # Setting polynomial degree to 4
X_poly_train = poly_reg.fit_transform(X_train)  # Transform training data to polynomial form

# Training the Polynomial Regression model
regressor = LinearRegression()  # Creating the Linear Regression model
regressor.fit(X_poly_train, y_train)  # Training the model on transformed training data

# Making Predictions on the Test Set
y_pred = regressor.predict(poly_reg.transform(X_test))  # Transform test data & predict

# Displaying the Predicted vs Actual Values
np.set_printoptions(precision=2)  # Set precision for better readability
print("\nPredicted vs Actual values:\n")
print(np.concatenate((y_pred.reshape(len(y_pred), 1), y_test.reshape(len(y_test), 1)), 1))

# Evaluating the Model
from sklearn.metrics import r2_score
r2 = r2_score(y_test, y_pred)  # Compute R² score
print("\nR² Score: {:.2f}".format(r2))  # Print R² score with two decimal places



Predicted vs Actual values:

[[434.16 431.23]
 [458.26 460.01]
 [460.72 461.14]
 ...
 [469.49 473.26]
 [438.53 438.  ]
 [461.62 463.28]]

R² Score: 0.95


In [4]:
# Random Forest Regression

# Importing necessary libraries
import numpy as np  # For numerical operations
import matplotlib.pyplot as plt  # For visualization
import pandas as pd  # For handling datasets

# Importing the dataset
dataset = pd.read_csv('Data.csv')  # Load dataset (replace with actual filename)
X = dataset.iloc[:, :-1].values  # Selecting independent variables (features)
y = dataset.iloc[:, -1].values  # Selecting dependent variable (target)

# Splitting the dataset into Training and Test sets
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)
# 80% training data, 20% testing data

# Training the Random Forest Regression model
from sklearn.ensemble import RandomForestRegressor
regressor = RandomForestRegressor(n_estimators=10, random_state=0)  # 10 decision trees in the forest
regressor.fit(X_train, y_train)  # Training the model

# Making Predictions on the Test Set
y_pred = regressor.predict(X_test)

# Displaying the Predicted vs Actual Values
np.set_printoptions(precision=2)  # Set precision for better readability
print("\nPredicted vs Actual values:\n")
print(np.concatenate((y_pred.reshape(len(y_pred), 1), y_test.reshape(len(y_test), 1)), 1))

# Evaluating the Model
from sklearn.metrics import r2_score
r2 = r2_score(y_test, y_pred)  # Compute R² score
print("\nR² Score: {:.2f}".format(r2))  # Print R² score with two decimal places



Predicted vs Actual values:

[[434.05 431.23]
 [458.79 460.01]
 [463.02 461.14]
 ...
 [469.48 473.26]
 [439.57 438.  ]
 [460.38 463.28]]

R² Score: 0.96


In [5]:
# Support Vector Regression (SVR)

# Importing necessary libraries
import numpy as np  # For numerical operations
import matplotlib.pyplot as plt  # For visualization
import pandas as pd  # For handling datasets

# Importing the dataset
dataset = pd.read_csv('Data.csv')  # Load dataset (replace with actual filename)
X = dataset.iloc[:, :-1].values  # Selecting independent variables (features)
y = dataset.iloc[:, -1].values  # Selecting dependent variable (target)

# Reshaping y to be a 2D array (required for feature scaling)
y = y.reshape(len(y), 1)

# Splitting the dataset into Training and Test sets
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)
# 80% training data, 20% testing data

# Feature Scaling (important for SVR)
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
sc_y = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)
y_train = sc_y.fit_transform(y_train)  # Target variable must also be scaled

# Training the Support Vector Regression model
from sklearn.svm import SVR
regressor = SVR(kernel='rbf')  # Using Radial Basis Function (RBF) kernel
regressor.fit(X_train, y_train.ravel())  # Flatten y_train to avoid errors

# Making Predictions on the Test Set
y_pred_scaled = regressor.predict(X_test)  # Predicting on scaled test data
y_pred = sc_y.inverse_transform(y_pred_scaled.reshape(-1, 1))  # Inverse scaling

# Displaying the Predicted vs Actual Values
np.set_printoptions(precision=2)  # Set precision for better readability
print("\nPredicted vs Actual values:\n")
print(np.concatenate((y_pred, y_test), 1))  # Print side-by-side comparison

# Evaluating the Model
from sklearn.metrics import r2_score
r2 = r2_score(y_test, y_pred)  # Compute R² score
print("\nR² Score: {:.2f}".format(r2))  # Print R² score with two decimal places



Predicted vs Actual values:

[[434.05 431.23]
 [457.94 460.01]
 [461.03 461.14]
 ...
 [470.6  473.26]
 [439.42 438.  ]
 [460.92 463.28]]

R² Score: 0.95
